<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>RS-FISH-Spark</artifactId>
    <version>0.0.3-SNAPSHOT</version>

    <parent>
        <groupId>org.scijava</groupId>
        <artifactId>pom-scijava</artifactId>
        <version>44.0.0</version>
        <relativePath/>
    </parent>

    <name>RS-FISH Spark</name>
    <description>Spark-based parallel radial symmetry localization on smFISH (and other) images.</description>
    <url>https://imagej.net/Radial_Symmetry</url>
    <inceptionYear>2021</inceptionYear>
    <organization>
        <name>Fiji</name>
        <url>http://fiji.sc/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU General Public License v2+</name>
            <url>http://www.gnu.org/licenses/gpl.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>StephanPreibisch</id>
            <name>Stephan Preibisch</name>
            <url>http://imagej.net/User:StephanP</url>
            <roles>
                <role>founder</role>
                <role>lead</role>
                <role>developer</role>
                <role>debugger</role>
                <role>reviewer</role>
                <role>support</role>
                <role>maintainer</role>
            </roles>
        </developer>
        <developer>
            <id>milkyklim</id>
            <name>Klim Kolyvanov</name>
            <url>http://imagej.net/User:MilkyKlim</url>
            <roles>
                <role>developer</role>
                <role>debugger</role>
                <role>reviewer</role>
                <role>support</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Timmothee Lionnet</name>
            <url>https://med.nyu.edu/faculty/timothee-lionnet</url>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>ImageJ Forum</name>
            <archive>http://forum.imagej.net/</archive>
        </mailingList>
    </mailingLists>

    <scm>
        <connection>scm:git:git://github.com/milkyklim/RadialSymmetryLocalization</connection>
        <developerConnection>scm:git:git@github.com:milkyklim/RadialSymmetryLocalization</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/milkyklim/RadialSymmetryLocalization</url>
    </scm>
    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/milkyklim/RadialSymmetryLocalization/issues</url>
    </issueManagement>
    <ciManagement>
        <system>Travis CI</system>
        <url>https://travis-ci.org/milkyklim/RadialSymmetryLocalization</url>
    </ciManagement>

    <properties>
        <license.licenseName>gpl_v2</license.licenseName>
        <license.copyrightOwners>Developers.</license.copyrightOwners>
        <scijava.jvm.version>21</scijava.jvm.version>

        <n5.version>4.0.0</n5.version>
        <n5-aws-s3.version>5.0.0</n5-aws-s3.version>
        <n5-hdf5.version>3.0.0</n5-hdf5.version>
        <n5-imglib2.version>8.0.0</n5-imglib2.version>
        <n5-universe.version>3.0.0</n5-universe.version>
        <n5-zarr.version>2.0.1</n5-zarr.version>
        <n5-zstandard.version>2.0.0</n5-zstandard.version>
        <n5-blosc.version>2.0.0</n5-blosc.version>

    </properties>
    <repositories>
        <!-- NB: for project parent -->
        <repository>
            <id>imagej.public</id>
            <url>https://maven.imagej.net/content/groups/public</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>net.preibisch</groupId>
            <artifactId>Radial_SymmetryLocalization</artifactId>
            <version>2.4.0</version>
            <exclusions>
                <exclusion>
                    <groupId>ome</groupId>
                    <artifactId>formats-bsd</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.openmicroscopy</groupId>
                    <artifactId>ome-common</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.janelia.saalfeldlab</groupId>
            <artifactId>n5-universe</artifactId>
            <version>${n5-universe.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.annotation</groupId>
                    <artifactId>javax.annotation-api</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
        <dependency>
            <groupId>org.janelia.saalfeldlab</groupId>
            <artifactId>n5</artifactId>
            <version>${n5.version}</version>
        </dependency>
        <dependency>
            <groupId>org.janelia.saalfeldlab</groupId>
            <artifactId>n5-zarr</artifactId>
            <version>${n5-zarr.version}</version>
        </dependency>
        <dependency>
            <groupId>org.janelia.saalfeldlab</groupId>
            <artifactId>n5-aws-s3</artifactId>
            <version>${n5-aws-s3.version}</version>
            <exclusions>
                <!-- netty-all already provides all io.netty classes; exclude individual modules to avoid duplicate class conflicts -->
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.7.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <!-- Scala is sensitive to fasterxml version -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.21.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.21</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <!-- Spark 4.1.2 comes with scala 2.13 -->
            <artifactId>spark-core_2.13</artifactId>
            <version>4.1.2</version>
            <exclusions>
                <exclusion>
                    <artifactId>jcl-over-slf4j</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jul-to-slf4j</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>log4j-slf4j-impl</artifactId>
                    <groupId>org.apache.logging.log4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>aopalliance-repackaged</artifactId>
                    <groupId>org.glassfish.hk2.external</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>javax.inject</artifactId>
                    <groupId>org.glassfish.hk2.external</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jersey-client</artifactId>
                    <groupId>org.glassfish.jersey.core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jersey-core</artifactId>
                    <groupId>com.sun.jersey</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>lz4</artifactId>
                    <groupId>net.jpountz.lz4</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jets3t</artifactId>
                    <groupId>net.java.dev.jets3t</groupId>
                </exclusion>
                <exclusion>
                    <groupId>javax.xml.stream</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.13.17</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
    </dependencies>
    <groupId>net.preibisch</groupId>
    <build>
        <finalName>RS-Fish</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <shadedClassifierName>with-dependencies</shadedClassifierName>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <!-- Do not minimize for now to speed up packaging. -->
                    <transformers combine.children="append">
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/json/org.janelia.saalfeldlab.n5.Compression$CompressionType</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/json/org.janelia.saalfeldlab.n5.serialization.NameConfig$Name</resource>
                        </transformer>
                    </transformers>
                    <!--<minimizeJar>true</minimizeJar> -->
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>Angle0.tif</exclude>
                                <exclude>LICENSE</exclude>
                                <exclude>LICENSE.txt</exclude>
                                <exclude>META-INF/DEPENDENCIES</exclude>
                                <exclude>META-INF/LICENSE</exclude>
                                <exclude>META-INF/NOTICE</exclude>
                                <exclude>META-INF/BSDL</exclude>
                                <exclude>META-INF/COPYING</exclude>
                                <exclude>META-INF/LEGAL</exclude>
                                <exclude>META-INF/LICENSE.RUBY</exclude>
                                <exclude>META-INF/json/org.scijava.plugin.Plugin</exclude>
                                <exclude>META-INF/*.MF</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                                <exclude>META-INF/*.txt</exclude>
                                <exclude>module-info.class</exclude>
                                <exclude>plugins.config</exclude>
                                <exclude>META-INF/versions/9/module-info.class</exclude>
                                <exclude>META-INF/okio.kotlin_module</exclude>
                                <exclude>META-INF/services/com.fasterxml.jackson.core.JsonFactory</exclude>
                            </excludes>
                        </filter>
                    </filters>
                    <!-- Additional configuration. -->
                    <artifactSet>
                        <excludes>
                            <exclude>xpp3:xpp3</exclude>
                        </excludes>
                    </artifactSet>
                    <relocations>
                        <relocation>
                            <pattern>org.apache.commons.compress</pattern>
                            <shadedPattern>org.janelia.saalfeldlab.org.apache.commons.compress</shadedPattern>
                        </relocation>
                        <!-- Protect newer gson version from the old one preloaded by spark -->
                        <relocation>
                            <pattern>com.google.gson</pattern>
                            <shadedPattern>org.janelia.saalfeldlab.com.google.gson</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <!-- binds by default to package phase -->
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
